export const FETCH_SUBCATEGORIES_STARTED = "FETCH_SUBCATEGORIES_STARTED";
export const FETCH_SUBCATEGORIES_FAILURE = "FETCH_SUBCATEGORIES_FAILURE";
export const FETCH_SUBCATEGORIES_SUCCESS = "FETCH_SUBCATEGORIES_SUCCESS";
