export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAILURE = "ADD_SUBCATEGORY_FAILURE";
export const FETCH_SUBCATEGORY_STARTED = "FETCH_SUBCATEGORY_STARTED";
export const FETCH_SUBCATEGORY_FAILURE = "FETCH_SUBCATEGORY_FAILURE";
export const FETCH_SUBCATEGORY_SUCCESS = "FETCH_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_FAILURE = "UPDATE_SUBCATEGORY_FAILURE";
