export const FETCH_IMAGES_STARTED = "FETCH_IMAGES_STARTED";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";
export const IMAGES_DELETE_SUCCESS = "IMAGES_DELETE_SUCCESS";
export const IMAGES_DELETE_FAILURE = "IMAGES_DELETE_FAILURE";
