export const FETCH_PRODUCTS_SUBCATEGORIES_STARTED =
  "FETCH_PRODUCTS_SUBCATEGORIES_STARTED";
export const FETCH_PRODUCTS_SUBCATEGORIES_SUCCESS =
  "FETCH_PRODUCTS_SUBCATEGORIES_SUCCESS";
export const FETCH_PRODUCTS_SUBCATEGORIES_FAILURE =
  "FETCH_PRODUCTS_SUBCATEGORIES_FAILURE";
